### ISSUE TITLE
packages installed via this module continually reinstall

### ISSUE THREAD

**Issue by andersje** [forward3d/puppet-r#2]
At every package run, I'm seeing my packages get reinstalled:

Info: Applying configuration version '1401905339'
Notice: /Stage[main]/Main/Node[rshiny2.mydomain.com]/R::Package[rCharts]/Exec[install_r_package_rCharts]/returns: executed successfully
Notice: /Stage[main]/Main/Node[rshiny2.mydomain.com]/R::Package[shiny]/Exec[install_r_package_shiny]/returns: executed successfully
Notice: /Stage[main]/Main/Node[rshiny2.mydomain.com]/R::Package[ggplot2]/Exec[install_r_package_ggplot2]/returns: executed successfully
Notice: /Stage[main]/Main/Node[rshiny2.mydomain.com]/R::Package[ROCR]/Exec[install_r_package_ROCR]/returns: executed successfully
Notice: /Stage[main]/Main/Node[rshiny2.mydomain.com]/R::Package[mapproj]/Exec[install_r_package_mapproj]/returns: executed successfully
Notice: /Stage[main]/Main/Node[rshiny2.mydomain.com]/R::Package[leaflet]/Exec[install_r_package_leaflet]/returns: executed successfully
Notice: Finished catalog run in 21.41 seconds

**Comment by boydj** [comment]
I'm also seeing this issue (but only with some packages, not all of them).

**Comment by andersje** [comment]
Hi @boydj -- did you resolve this?  did installing EPEL help?

**Comment by boydj** [comment]
I think I did, not working on that project anymore. This is what my R manifest looked like.

`class boydj::r inherits morpheus{
  file { 'miniCRAN':
    path => '/usr/local/src/miniCRAN',
    ensure => directory,
    source => 'puppet:///modules/boydj/r/miniCRAN',
    recurse => true,
  }

  class { '::r': }

  ::r::package { 'dplyr': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'e1071': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'gplots': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'highr': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'igraph': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'kernlab': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'lubridate': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'plyr': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'qcc': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'ROCR': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'RODBC': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'rpca': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'RSQLite': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'shiny': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'sqldf': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'testthat': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }

  ::r::package { 'wavelets': repo => 'file:///usr/local/src/miniCRAN', dependencies => true, }
}`
